#!/bin/zsh

error() {
    yad --center --text "$1"
    exit 1
}

[[ -n "$1" ]] || error "Input file required."
[[ -r "$1" ]] || error "Cannot read the ical file \'$1\'."

TMPFILE="$(mktemp --tmpdir XXXXXX.rem)"
trap "[[ -w $TMPFILE ]] && rm $TMPFILE" EXIT

ical2rem "$1" > $TMPFILE

[[ -s "$TMPFILE" ]] || error "Failed to parse \'$1\'."

for file in ~/.reminders/*; do
    CHOICES="$CHOICES!$(basename $file .rem)"
done;

CHOICES="${CHOICES##\!}"

IFS="|" OUTPUT=($(yad --center --text "Add reminders to calendar:\n\n$(remind -t $TMPFILE|sed -e '1d' -e '/^$/d' -e 's/&/&amp;/g' -e 's/</&lt;/g' -e 's/>/&gt;/g' | fold -s)" --form --field="Calendar:CBE" "$CHOICES"))

[[ $? -eq 0 ]] && <$TMPFILE>>~/.reminders/${OUTPUT[1]}.rem
