#!/bin/sh
export DISPLAY=${DISPLAY:-:0}

xrandr -display $DISPLAY -q | awk 'BEGIN {
}

($2 == "connected"){
    dev=$1
    getline
    mode=$1
    on_screens[dev]=mode
}
($2 == "disconnected"){
    off_screens[$1]=$1
}

END {
    CMD="xrandr -display "ENVIRON["DISPLAY"]
    CMD=CMD" --output LVDS1 --mode "on_screens["LVDS1"]
    delete on_screens["LVDS1"]
    PREV="LVDS1"
    for (screen in on_screens) {
        CMD=CMD" --output "screen" --mode "on_screens[screen]" --right-of "PREV
        PREV=screen
    }
    CMD=CMD" --primary"
    for (screen in off_screens) {
        CMD=CMD" --output "screen" --off"
    }
    system(CMD)
}'
