#!/bin/zsh

case $1 in
    run)
        dmenu_run -b
        ;;
    moc)
        moc_parse() {
            cat | awk '
BEGIN {
    FS=","
    dmenu="dmenu -l 10 -b -i -nb \"" ENVIRON["nb"] "\" -nf \"" ENVIRON["nf"] "\" -sf \"" ENVIRON["sf"] "\" -sb \"" ENVIRON["sb"] "\""
}

/^#EXTINF/ {
    sub(/.$/, "", $2)
    title=$2
    print title |& dmenu
}

/^\// {
    sub(/.$/, "", $0)
    playlist[title]=$0
}

END {
    close(dmenu, "to")
    dmenu |& getline
    close(dmenu)
    print playlist[$0]
}
'
        }
        file="$(cat ~/.moc/playlist.m3u | moc_parse)"
        exec mocp -l "$file"
    ;;
    mpd)
        exec mpc play $(sed -n "s@^ *\([0-9]\+\);$(mpc playlist|dmenu -b -i -l 10 -p 'song name'||echo ";;;")@\1@p" < <(mpc playlist|nl -s ';'))
        ;;
    launch)
        exec dmenu-launch
        ;;
    power)
        case $(dmenu -b -i -p "Power:" -l 5 <<-EOF
Shutdown
Restart
Logout
Suspend
Lock
EOF) in
            Shutdown)
                exec systemctl poweroff;;
            Restart)
                exec systemctl reboot;;
            Logout)
                exec systemctl --user exit;;
            Suspend)
                exec systemctl suspend;;
            Lock)
                exec systemctl --user start lock.target;;
        esac
        ;;
    run-awesome)
        XDG_CACHE_HOME=${XDG_CACHE_HOME:-"$HOME/.cache"}
        if ! test -d "$XDG_CACHE_HOME/awesome"; then
            mkdir -p "$XDG_CACHE_HOME/awesome"
        fi
        HISTORY=$XDG_CACHE_HOME/awesome/history
        CACHE=$XDG_CACHE_HOME/dmenu_cache

        [[ -e $HISTORY ]] || touch $HISTORY
        [[ -e $CACHE ]] || touch $CACHE

        if stest -dqr -n "$CACHE" $path; then
            stest -flx $path | sort -ur > "$CACHE"
        fi
        cmd=$(tac $HISTORY $CACHE | dmenu -b -i)
        [[ -z "$cmd" ]] && exit
        echo $cmd >> "$HISTORY"
        exec eval $cmd
        ;;
esac
