#!/bin/bash

[ $(id -u) -eq 0 ] || SUDO="sudo"

cmd_error () {
    echo -e "\e[31;1merror:\e[37;1m '$1'\e[0m" is not a valid command.
    exit 1
}
arg_error () {
    echo -e "\e[31;1merror:\e[37;1m '$1'\e[0m" requires an argument.
    exit 1
}

case $1 in
    u)
        exec packer -Syu -Syu
        exit 0
        ;;
    c)
        $SUDO pacman-color -Sc --noconfirm
        $SUDO pacman-optimize
        $SUDO localepurge
        exit 0
        ;;
    lost)
        exec pacman-color -Qdt
        exit 0
        ;;
    -*)
        exec $SUDO pacman-color $*
        exit 0
        ;;
    i)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec packer -S $*
        ;;
    li)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec $SUDO pacman-color -U $*
        ;;
    r)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec $SUDO pacman-color -Rsn $*
        ;;
    x)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec packer -Si $*
        ;;
    lx)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec pacman-color -Qi $*
        ;;
    l)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec pacman-color -Ql $*
        ;;
    o)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec pacman-color -Qo $*
        ;;
    s)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec packer -Ss $*
        ;;
    ls)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec pacman-color -Qs $*
        ;;
    src)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec pbget --aur $*
        ;;
    g)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec pacman-color -Qg $*
        ;;
    .)
        [ $# -gt 1 ] || arg_error $1
        shift 1
        exec $SUDO pacman-color $*
        ;;
    *)
        cmd_error $1
        ;;
esac

